Movies js route
connorkent21/top-secret-htn-project pull request #3
Opened 2021-01-17 02:05 UTC by dlrobson

2021-01-17 02:08 UTC, dlrobson commented on client/src/app/index.js
> -          <Route eaxct path="/" component={LandingView} />
eaxct??

2021-01-17 02:08 UTC, connorkent21 requested changes
smh

2021-01-17 02:08 UTC, connorkent21 commented on client/src/api/Movies.js
> +  return null;
should return an error status

2021-01-17 02:08 UTC, connorkent21 commented on client/src/app/components/Navigation.jsx
> +    const res = GetMoviesByGenre();
Missing params???

2021-01-17 02:08 UTC, connorkent21 commented on client/src/app/index.js
> +  return (<ThemeProvider theme = {MaterialTheme}><Router><Navigation /><Switch><
bro wtf is this???????????

2021-01-17 02:08 UTC, connorkent21 commented on client/src/app/index.js
> +          Route eaxct path = "/" component = {LandingView} /></ Switch><
**exact

2021-01-17 02:08 UTC, connorkent21 commented on server/routes/movies.js
> +  // // const {id} = req.body;
smh

2023-08-15 21:38 UTC, dlrobson commented
:(

2023-08-18 02:58 UTC, connorkent21 commented
Bringing it back???

2023-08-18 13:01 UTC, richardbarina commented
Lol hackathon 2023 here we come

On Thu, Aug 17, 2023 at 10:58 PM Connor Kent ***@***.***>
wrote:

> Bringing it back???
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/connorkent21/top-secret-htn-project/pull/3#issuecomment-1683265914>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASPVSQC75V62T2UB3OKAI63XV3K43ANCNFSM4WFXAPCA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2026-03-02 01:50 UTC, closed without merging